# Generated by Django 2.1.7 on 2020-06-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
        migrations.AddField(
            model_name='post',
            name='payment_status',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete')], default='incomplete', max_length=50),
        ),
    ]
